site_name: My Docs
theme: readthedocs
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML', 'mathjaxconfig.js']
pages:
- 'Introduction': 'index.md'
- '1 Introduction':
    - '1.1 Language Processors': '1-Introduction/1.1-Language-Processors.md'
    - '1.3 The Evolution of Programming Languages': '1-Introduction/1.3-The-Evolution-of-Programming-Languages.md'
    - '1.6 Programming Language Basics': '1-Introduction/1.6-Programming-Language-Basics.md'
- '2 A Simple Syntax-Directed Translator':
    - '2.2 Syntax Definition': '2-A-Simple-Syntax-Directed-Translator/2.2-Syntax-Definition.md'
    - '2.3 Syntax-Directed Translation': '2-A-Simple-Syntax-Directed-Translator/2.3-Syntax-Directed-Translation.md'
    - '2.4 Parsing': '2-A-Simple-Syntax-Directed-Translator/2.4-Parsing.md'
    - '2.6 Lexical Analysis': '2-A-Simple-Syntax-Directed-Translator/2.6-Lexical-Analysis.md'
    - '2.8 Intermediate Code Generation': '2-A-Simple-Syntax-Directed-Translator/2.8-Intermediate-Code-Generation.md'
- '3 Lexical Analysis':
    - '3.1 The Role of the Lexical Analyzer': '3-Lexical-Analysis/3.1-The-Role-of-The-Lexical-Analyzer.md'